In [1]:
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.tree import export_graphviz
import pydotplus 
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn import linear_model 

In [62]:
iperf1 = pd.read_csv('/Users/xiongzhaoqi/Cambridge/Project/traces1000/iperf.csv')
iperf1 = iperf1.drop('protocl',axis=1)
iperf = iperf1.values.tolist()
memcached1 = pd.read_csv('/Users/xiongzhaoqi/Cambridge/Project/traces1000/memcached.csv')
memcached1 = memcached1.drop('protocl',axis=1)
memcached = memcached1.values.tolist()
# ping1 = pd.read_csv('/Users/xiongzhaoqi/Cambridge/Project/traces1000/ping.csv')
# ping = ping1.values.tolist()
# sparkglm1 = pd.read_csv('/Users/xiongzhaoqi/Cambridge/Project/traces1000/sparkglm.csv')
# sparkglm = sparkglm1.values.tolist()
# sparkkmeans1 = pd.read_csv('/Users/xiongzhaoqi/Cambridge/Project/traces1000/sparkkmeans.csv')
# sparkkmeans = sparkkmeans1.values.tolist()
X = iperf+ memcached # + ping + sparkglm + sparkkmeans
#X = memcached + ping 
Y = 1000*[0] + 1000*[1]  #+ 1000*[2] + 1000*[3] + 1000* [4]

In [63]:
X = np.array(X)
Y = np.array(Y)

In [64]:
print(X)

[[ 5001  5001]
 [ 5001  5001]
 [ 5001  5001]
 ...
 [11211 38508]
 [38412 11211]
 [38600 11211]]


In [65]:
indices = np.random.permutation(len(X))

In [66]:
print(indices)

[ 754 1432  135 ...  202 1190  957]


In [67]:
Training_X = X[indices[:-200]] 
Training_Y = Y[indices[:-200]]
Testing_X = X[indices[-200:]]
Testing_Y = Y[indices[-200:]]

In [68]:
clf = SVC(kernel = 'linear')
clf.fit(Training_X, Training_Y ) 


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [69]:
Train = clf.predict(Training_X )
print(accuracy_score(Training_Y, Train))


1.0


In [70]:
# Predict_Y = clf.predict(Testing_X)
Predict_Y = clf.predict(Testing_X)
print(classification_report(Testing_Y, Predict_Y))
print(accuracy_score(Testing_Y, Predict_Y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       109
           1       1.00      1.00      1.00        91

   micro avg       1.00      1.00      1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

1.0


In [71]:
print(clf.coef_)
print(clf.intercept_)


[[5.05068736e-05 5.05359258e-05]]
[-1.5055782]
