In [2]:
from scapy.all import * 
from scapy.layers.dns import DNS, DNSQR 
import numpy as np
import pandas as pd

# iperf

In [6]:
results = []
#iperf（client and server）
all_packets = rdpcap('/Users/xiongzhaoqi/traces/iperf/server.cap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0f
        dport = 0
#     metric = [proto,sport,dport,size,checksum]
    difference = abs(sport - dport)
    metric = [proto,sport,dport,size,difference]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[   6    6    6 ...    6    6    6]
 [5001 5001 5001 ... 5001 5001 5001]
 [5001 5001 5001 ... 5001 5001 5001]
 [  74   74   66 ...   66   66   66]
 [   0    0    0 ...    0    0    0]]


In [7]:
# dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'checksum':results[4]})
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'difference':results[4]})

In [8]:
# columns = ['protocl','src','dst','size','checksum']
columns = ['protocl','src','dst','size','difference']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/tracesall/iperf/server.csv",index=False,sep=',',columns = columns)

# Memcached

In [ ]:
results = []
# memcached (expt1 ,2,3)
all_packets = rdpcap('/Users/xiongzhaoqi/traces/memcached/expt-1.cap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport,size,difference]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

In [7]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'difference':results[4]})
columns = ['protocl','src','dst','size','difference']
# columns = ['protocl','src','dst','size','checksum']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/tracesall/memcached/expt-1.csv",index=False,sep=',',columns = columns)

# TCPdump

In [8]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/ping.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport,size,difference]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[ 1  1  1 ...  1  1  1]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [98 98 98 ... 98 98 98]
 [ 0  0  0 ...  0  0  0]]


In [9]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'difference':results[4]})
columns = ['protocl','src','dst','size','difference']
# columns = ['protocl','src','dst','size','checksum']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/ping.csv",index=False,sep=',',columns = columns)

# Sparkglm

In [10]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/sparkglm.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport,size,difference]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[    6     6     6 ...     6     6     6]
 [42830 42830  7077 ... 38237 38237 34816]
 [ 7077  7077 42830 ... 34816 34816 38237]
 [   79  1514    66 ...    87   113    66]
 [35753 35753 35753 ...  3421  3421  3421]]


In [11]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'difference':results[4]})
columns = ['protocl','src','dst','size','difference']
# columns = ['protocl','src','dst','size','checksum']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/sparkglm.csv",index=False,sep=',',columns = columns)

# Sparkkmeans

In [12]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/sparkkmeans.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport,size,difference]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[    6     6     6 ...     6     6     6]
 [42830 42830  7077 ... 46299 50176 50176]
 [ 7077  7077 42830 ... 50176 46299 46299]
 [   79  1514    66 ...    66 56306  8502]
 [35753 35753 35753 ...  3877  3877  3877]]


In [13]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'difference':results[4]})
columns = ['protocl','src','dst','size']
columns = ['protocl','src','dst','size','difference']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/sparkkmeans.csv",index=False,sep=',',columns = columns)