In [1]:
from scapy.all import * 
from scapy.layers.dns import DNS, DNSQR 
import numpy as np

In [2]:
iperf = []
iperf_packets = rdpcap('/Users/xiongzhaoqi/traces2/iperf/client.cap') 
packet = iperf_packets[1]
print(packet.show())
# for packet in iperf_packets:
#     metric = [packet.proto,packet.sport,packet.dport,len(packet)]
#     iperf.append(metric)
# iperf = np.array(iperf)
# print(iperf[0:20])

###[ Ethernet ]### 
  dst       = 00:0d:3a:4e:59:a5
  src       = 74:83:ef:6a:80:97
  type      = 0x800
###[ IP ]### 
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 60
     id        = 0
     flags     = DF
     frag      = 0
     ttl       = 64
     proto     = tcp
     chksum    = 0x26a8
     src       = 10.0.0.10
     dst       = 10.0.0.11
     \options   \
###[ TCP ]### 
        sport     = commplex_link
        dport     = commplex_link
        seq       = 814113331
        ack       = 3502425558
        dataofs   = 10
        reserved  = 0
        flags     = SA
        window    = 28960
        chksum    = 0x2ca2
        urgptr    = 0
        options   = [('MSS', 1418), ('SAckOK', ''), ('Timestamp', (750183140, 1229384956)), ('NOP', None), ('WScale', 7)]

None


In [7]:
cache = []
cache_packets = rdpcap('/Users/xiongzhaoqi/traces2/memcached/expt-1.pcap') 
packet = cache_packets[0]
print(packet.show())
# for packet in cache_packets:
#     metric = [packet.proto,packet.sport,packet.dport,len(packet)]
#     cache.append(metric)
# cache = np.array(cache)
# print(cache[0:20])


###[ Ethernet ]### 
  dst       = 12:34:56:78:9a:bc
  src       = 00:0d:3a:1e:06:c0
  type      = 0x800
###[ IP ]### 
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 93
     id        = 23221
     flags     = DF
     frag      = 0
     ttl       = 64
     proto     = tcp
     chksum    = 0xc5da
     src       = 10.0.3.7
     dst       = 10.0.3.5
     \options   \
###[ TCP ]### 
        sport     = 11211
        dport     = 38094
        seq       = 807868590
        ack       = 3850087914
        dataofs   = 8
        reserved  = 0
        flags     = PA
        window    = 325
        chksum    = 0x1a5b
        urgptr    = 0
        options   = [('NOP', None), ('NOP', None), ('Timestamp', (3496865280, 205696067))]
###[ Raw ]### 
           load      = 'VALUE 00000000000000009733 0 2\r\nle\r\nEND\r\n'

None


In [8]:
ping = []
ping_packets = rdpcap('/Users/xiongzhaoqi/traces2/ping/tcpdump.pcap') 
packet = ping_packets[0]
print(packet.show())
# for packet in ping_packets:
#     metric = [packet.proto,len(packet)]
#     ping.append(metric)
# ping = np.array(ping)
# print(ping[0:20])

###[ Ethernet ]### 
  dst       = 00:0d:3a:1b:6f:23
  src       = 00:42:68:64:7f:ef
  type      = 0x800
###[ IP ]### 
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 84
     id        = 10114
     flags     = DF
     frag      = 0
     ttl       = 64
     proto     = icmp
     chksum    = 0xff1e
     src       = 10.0.0.4
     dst       = 10.0.0.5
     \options   \
###[ ICMP ]### 
        type      = echo-request
        code      = 0
        chksum    = 0xb0b2
        id        = 0x36d9
        seq       = 0x1
###[ Raw ]### 
           load      = '\xf9\x8b\x17[\x00\x00\x00\x00:\xb9\x06\x00\x00\x00\x00\x00\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./01234567'

None


In [12]:
sparkglm = []
sparkglm_packets = rdpcap('/Users/xiongzhaoqi/traces2/sparkglm/slave1.cap') 
for packet in sparkglm_packets:
    metric = [packet.proto,packet.sport,packet.dport,len(packet)]
    sparkglm.append(metric)
sparkglm = np.array(sparkglm)
print(sparkglm[0:20])



[[    6 42830  7077    79]
 [    6 42830  7077  1514]
 [    6  7077 42830    66]
 [    6 42830  7077    79]
 [    6 42830  7077  1514]
 [    6  7077 42830    66]
 [    6 56808    22    74]
 [    6    22 56808    74]
 [    6 56808    22    66]
 [    6 56808    22   107]
 [    6    22 56808    66]
 [    6    22 56808   107]
 [    6 56808    22    66]
 [    6    22 56808  1042]
 [    6 56808    22  1402]
 [    6    22 56808    66]
 [    6 56808    22   114]
 [    6    22 56808    66]
 [    6    22 56808   430]
 [    6 56808    22    82]]


In [15]:
sparkkmeans = []
sparkkmeans_packets = rdpcap('/Users/xiongzhaoqi/traces2/sparkkmeans/master.pcap') 
for packet in sparkkmeans_packets:
    metric = [packet.proto,packet.sport,packet.dport,len(packet)]
    sparkkmeans.append(metric)
sparkkmeans = np.array(sparkkmeans)
print(sparkkmeans[0:20])



[[    6 42830  7077    79]
 [    6 42830  7077  1514]
 [    6  7077 42830    66]
 [    6 42830  7077    79]
 [    6 42830  7077  1514]
 [    6  7077 42830    66]
 [    6 42010    22    74]
 [    6    22 42010    74]
 [    6 42010    22    66]
 [    6 42010    22   107]
 [    6    22 42010    66]
 [    6    22 42010   107]
 [    6 42010    22    66]
 [    6 42010    22  1402]
 [    6    22 42010  1042]
 [    6    22 42010    66]
 [    6 42010    22   114]
 [    6    22 42010    66]
 [    6    22 42010   430]
 [    6 42010    22    82]]
