In [13]:
from scapy.all import * 
from scapy.layers.dns import DNS, DNSQR 
import numpy as np
import pandas as pd

# iperf

In [14]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/iperf.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
#     metric = [proto,sport,dport,size,checksum]
    difference = abs(sport - dport)
    metric = [proto,sport,dport]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[   6    6    6 ...    6    6    6]
 [5001 5001 5001 ... 5001 5001 5001]
 [5001 5001 5001 ... 5001 5001 5001]]


In [15]:
# dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2],'size':results[3],'checksum':results[4]})
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2]})

In [16]:
# columns = ['protocl','src','dst','size','checksum']
columns = ['protocl','src','dst']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/iperf.csv",index=False,sep=',',columns = columns)

# Memcached

In [17]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/memcached.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[    6     6     6 ...     6     6     6]
 [38650 11211 38640 ... 11211 38412 38600]
 [11211 38526 11211 ... 38508 11211 11211]]


In [18]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2]})
columns = ['protocl','src','dst']
# columns = ['protocl','src','dst','size','checksum']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/memcached.csv",index=False,sep=',',columns = columns)

# TCPdump

In [19]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/ping.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2]})
columns = ['protocl','src','dst']
# columns = ['protocl','src','dst','size','checksum']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/ping.csv",index=False,sep=',',columns = columns)

# Sparkglm

In [22]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/sparkglm.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[    6     6     6 ...     6     6     6]
 [42830 42830  7077 ... 38237 38237 34816]
 [ 7077  7077 42830 ... 34816 34816 38237]]


In [23]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2]})
columns = ['protocl','src','dst']
# columns = ['protocl','src','dst','size','checksum']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/sparkglm.csv",index=False,sep=',',columns = columns)

# Sparkkmeans

In [24]:
results = []
all_packets = rdpcap('/Users/xiongzhaoqi/traces3/sparkkmeans.pcap') 
for packet in all_packets:
    proto = packet.proto
    size =  len(packet)
    checksum = packet.chksum
    try:
        sport = packet.sport
        dport = packet.dport
    except AttributeError:
        sport = 0
        dport = 0
    difference = abs(sport - dport)
    metric = [proto,sport,dport]
    results.append(metric)
results = (np.array(results)).T
print(results[0:20])

[[    6     6     6 ...     6     6     6]
 [42830 42830  7077 ... 46299 50176 50176]
 [ 7077  7077 42830 ... 50176 46299 46299]]


In [25]:
dataframe = pd.DataFrame({'protocl':results[0],'src':results[1],'dst':results[2]})
columns = ['protocl','src','dst','size']
columns = ['protocl','src','dst']
dataframe.to_csv("/Users/xiongzhaoqi/Cambridge/Project/traces1000/sparkkmeans.csv",index=False,sep=',',columns = columns)